set = "RV64Zfa"
width = 32

[formats]
names = [
    "format-1-1",
    "format-1-2",
    "format-2-3",
    "format-2-7",
    "format-3-3",
]
parts = [
    [
        "rd_Register_int",
        5,
        "Register_int",
    ],
    [
        "rd_Register_float",
        5,
        "Register_float",
    ],
    [
        "rs1_Register_int",
        5,
        "Register_int",
    ],
    [
        "rs1_Register_float",
        5,
        "Register_float",
    ],
    [
        "rs2_Register_int",
        5,
        "Register_int",
    ],
    [
        "rs2_Register_float",
        5,
        "Register_float",
    ],
    [
        "rm",
        3,
        "Mapping_round",
    ],
    [
        "none",
        32,
        "u32",
    ],
    [
        "imm",
        32,
        "VInt",
    ],
    [
        "himm",
        32,
        "VInt",
        "hex",
    ],
    [
        "lval",
        5,
        "Mapping_vals",
    ],
]

[types]
names = [
    "type-1-1",
    "type-1-2",
    "type-2-3",
    "type-2-7",
    "type-3-3",
]
type-1-1 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_int", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-1-2 = [
    { name = "none", top = 31, bot = 20 },
    { name = "lval", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-2-3 = [
    { name = "none", top = 31, bot = 25 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_int", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-2-7 = [
    { name = "none", top = 31, bot = 25 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-3-3 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]

[format-1-1]
type = "type-1-1"

[format-1-1.repr]
default = "$name$ %rd_Register_int%, %rs1_Register_float%, rtz"

[format-1-1.instructions."fcvtmod.w.d"]
mask = 4293947519
match = 3263172691

[[format-1-1.instructions."fcvtmod.w.d".description]]
id = "inst-fcvtmod.w.d-behaviour"
normative = false
text = "`fcvtmod.w.d` always rounds towards zero. Bits 31:0 are taken from the rounded, unbounded two's\ncomplement result, then sign-extended to XLEN bits and written to integer register `xd`.±∞ and\nNaN are converted to zero.\n\nFloating-point exception flags are raised the same as they would be for FCVT.W.D with the same input\noperand.\n\nThis instruction is only provided if the D extension is implemented. It is encoded like FCVT.W.D, but\nwith the `xs2` field set to 8 and the `rm` field set to 1 (RTZ). Other `rm` values are reserved.\n"

[format-1-2]
type = "type-1-2"

[format-1-2.repr]
default = "$name$ %rd_Register_float%, %lval%"

[format-1-2.instructions."fli.d"]
mask = 4293947519
match = 4061134931
description = "No description available.\n"

[format-1-2.instructions."fli.h"]
mask = 4293947519
match = 4094689363
description = "No description available.\n"

[format-2-3]
type = "type-2-3"

[format-2-3.repr]
default = "$name$ %rd_Register_int%, %rs1_Register_float%, %rs2_Register_float%"

[format-2-3.instructions."fleq.d"]
mask = 4261441663
match = 2717925459
description = "No description available.\n"

[format-2-3.instructions."fleq.h"]
mask = 4261441663
match = 2751479891
description = "No description available.\n"

[format-2-3.instructions."fltq.d"]
mask = 4261441663
match = 2717929555
description = "No description available.\n"

[format-2-3.instructions."fltq.h"]
mask = 4261441663
match = 2751483987
description = "No description available.\n"

[format-2-7]
type = "type-2-7"

[format-2-7.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_float%, %rs2_Register_float%"

[format-2-7.instructions."fmaxm.d"]
mask = 4261441663
match = 704655443
description = "No description available.\n"

[format-2-7.instructions."fmaxm.h"]
mask = 4261441663
match = 738209875
description = "No description available.\n"

[format-2-7.instructions."fminm.d"]
mask = 4261441663
match = 704651347
description = "No description available.\n"

[format-2-7.instructions."fminm.h"]
mask = 4261441663
match = 738205779
description = "No description available.\n"

[format-3-3]
type = "type-3-3"

[format-3-3.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_float%, %rm%"

[format-3-3.instructions."fround.d"]
mask = 4293918847
match = 1111490643
description = "No description available.\n"

[format-3-3.instructions."fround.h"]
mask = 4293918847
match = 1145045075
description = "No description available.\n"

[format-3-3.instructions."froundnx.d"]
mask = 4293918847
match = 1112539219
description = "No description available.\n"

[format-3-3.instructions."froundnx.h"]
mask = 4293918847
match = 1146093651
description = "No description available.\n"

[mappings]
names = [
    "Register_int",
    "Register_float",
    "Mapping_round",
    "Mapping_vals",
]
number = 32
Register_int = [
    "zero",
    "ra",
    "sp",
    "gp",
    "tp",
    "t0",
    "t1",
    "t2",
    "s0",
    "s1",
    "a0",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "s10",
    "s11",
    "t3",
    "t4",
    "t5",
    "t6",
]
Register_float = [
    "ft0",
    "ft1",
    "ft2",
    "ft3",
    "ft4",
    "ft5",
    "ft6",
    "ft7",
    "fs0",
    "fs1",
    "fa0",
    "fa1",
    "fa2",
    "fa3",
    "fa4",
    "fa5",
    "fa6",
    "fa7",
    "fs2",
    "fs3",
    "fs4",
    "fs5",
    "fs6",
    "fs7",
    "fs8",
    "fs9",
    "fs10",
    "fs11",
    "ft8",
    "ft9",
    "ft10",
    "ft11",
]
Mapping_round = [
    "rne",
    "rtz",
    "rdn",
    "rup",
    "rmm",
    "unknown",
    "unknown",
    "dyn",
]
Mapping_vals = [
    "-1.0",
    "min",
    "2.0e-16",
    "2.0e-15",
    "2.0e-8",
    "2.0e-7",
    "0.0625",
    "0.125",
    "0.25",
    "0.3125",
    "0.375",
    "0.4375",
    "0.5",
    "0.625",
    "0.75",
    "0.875",
    "1.0",
    "1.25",
    "1.5",
    "1.75",
    "2.0",
    "2.5",
    "3.0",
    "4.0",
    "8.0",
    "16.0",
    "128.0",
    "256.0",
    "32768.0",
    "65536.0",
    "inf",
    "nan",
]
