set = "RV64D"
width = 32

[formats]
names = [
    "format-1-7",
    "format-2-1",
    "format-2-2",
    "format-3-1",
    "format-3-2",
    "format-3-3",
    "format-4-3",
    "format-4-7",
    "format-5-0",
    "format-6-15",
    "format-7-0",
]
parts = [
    [
        "rd_Register_int",
        5,
        "Register_int",
    ],
    [
        "rd_Register_float",
        5,
        "Register_float",
    ],
    [
        "rs1_Register_int",
        5,
        "Register_int",
    ],
    [
        "rs1_Register_float",
        5,
        "Register_float",
    ],
    [
        "rs2_Register_int",
        5,
        "Register_int",
    ],
    [
        "rs2_Register_float",
        5,
        "Register_float",
    ],
    [
        "rm",
        3,
        "Mapping_round",
    ],
    [
        "rs3_Register_int",
        5,
        "Register_int",
    ],
    [
        "rs3_Register_float",
        5,
        "Register_float",
    ],
    [
        "none",
        32,
        "u32",
    ],
    [
        "imm",
        32,
        "VInt",
    ],
    [
        "himm",
        32,
        "VInt",
        "hex",
    ],
]

[types]
names = [
    "type-1-7",
    "type-2-1",
    "type-2-2",
    "type-3-1",
    "type-3-2",
    "type-3-3",
    "type-4-3",
    "type-4-7",
    "type-5-0",
    "type-6-15",
    "type-7-0",
]
type-1-7 = [
    { name = "none", top = 31, bot = 25 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-2-1 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_int", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-2-2 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_int", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-3-1 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rd_Register_int", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-3-2 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_int", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-3-3 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-4-3 = [
    { name = "none", top = 31, bot = 25 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_int", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-4-7 = [
    { name = "none", top = 31, bot = 25 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-5-0 = [
    { name = "imm", top = 11, bot = 0 },
    { name = "rs1_Register_int", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-6-15 = [
    { name = "rs3_Register_float", top = 4, bot = 0 },
    { name = "none", top = 26, bot = 25 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_float", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rd_Register_float", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type-7-0 = [
    { name = "imm", top = 11, bot = 5 },
    { name = "rs2_Register_float", top = 4, bot = 0 },
    { name = "rs1_Register_int", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "imm", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]

[format-1-7]
type = "type-1-7"

[format-1-7.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_float%, %rs2_Register_float%, %rm%"

[format-1-7.instructions."fadd.d"]
mask = 4261412991
match = 33554515

[[format-1-7.instructions."fadd.d".description]]
id = "inst-fadd.d-behaviour"
normative = false
text = "`fadd.d` is analogous to `fadd.s` and performs double-precision floating-point addition between\n`xs1` and `xs2` and writes the final result to `xd`.\n"

[format-1-7.instructions."fdiv.d"]
mask = 4261412991
match = 436207699
description = "No description available.\n"

[format-1-7.instructions."fmul.d"]
mask = 4261412991
match = 301989971
description = "No description available.\n"

[format-1-7.instructions."fsub.d"]
mask = 4261412991
match = 167772243
description = "No description available.\n"

[format-2-1]
type = "type-2-1"

[format-2-1.repr]
default = "$name$ %rd_Register_int%, %rs1_Register_float%"

[format-2-1.instructions."fclass.d"]
mask = 4293947519
match = 3791654995
description = "No description available.\n"

[format-2-1.instructions."fmv.x.d"]
mask = 4293947519
match = 3791650899
description = "No description available.\n"

[format-2-2]
type = "type-2-2"

[format-2-2.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_int%"

[format-2-2.instructions."fmv.d.x"]
mask = 4293947519
match = 4060086355
description = "No description available.\n"

[format-3-1]
type = "type-3-1"

[format-3-1.repr]
default = "$name$ %rd_Register_int%, %rs1_Register_float%, %rm%"

[format-3-1.instructions."fcvt.l.d"]
mask = 4293918847
match = 3256877139

[[format-3-1.instructions."fcvt.l.d".description]]
id = "inst-fcvt.l.d-behaviour"
normative = false
text = "`fcvt.l.d` converts a double-precision floating-point number in floating-point register `fs1`\nto a signed 64-bit integer, in integer register `xd`.\n"

[format-3-1.instructions."fcvt.lu.d"]
mask = 4293918847
match = 3257925715

[[format-3-1.instructions."fcvt.lu.d".description]]
id = "inst-fcvt.lu.d-behaviour"
normative = false
text = "`fcvt.lu.d` converts a double-precision floating-point number in floating-point register `xs1`\nto an unsigned 64-bit integer, in integer register `xd`.\n"

[format-3-1.instructions."fcvt.w.d"]
mask = 4293918847
match = 3254779987

[[format-3-1.instructions."fcvt.w.d".description]]
id = "inst-fcvt.w.d-behaviour"
normative = false
text = "`fcvt.w.d` converts a double-precision floating-point number in floating-point register `xs1` to a\nsigned 32-bit integer, in integer register `xd`.\n"

[format-3-1.instructions."fcvt.wu.d"]
mask = 4293918847
match = 3255828563

[[format-3-1.instructions."fcvt.wu.d".description]]
id = "inst-fcvt.wu.d-behaviour"
normative = false
text = "`fcvt.wu.d` converts a double-precision floating-point number in floating-point register `xs1` to an\nunsigned 32-bit integer, in integer register `fd`.\n"

[format-3-2]
type = "type-3-2"

[format-3-2.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_int%, %rm%"

[format-3-2.instructions."fcvt.d.l"]
mask = 4293918847
match = 3525312595

[[format-3-2.instructions."fcvt.d.l".description]]
id = "inst-fcvt.d.l-behaviour"
normative = false
text = "`fcvt.d.l` converts a 64-bit signed integer, in integer register `xs1` into a double-precision\nfloating-point number in floating-point register `fd`.\n"

[format-3-2.instructions."fcvt.d.lu"]
mask = 4293918847
match = 3526361171

[[format-3-2.instructions."fcvt.d.lu".description]]
id = "inst-fcvt.d.lu-behaviour"
normative = false
text = "`fcvt.d.lu` converts to or from a 64-bit unsigned integer, `xs1` into a double-precision\nfloating-point number in floating-point register `fd`.\n"

[format-3-2.instructions."fcvt.d.w"]
mask = 4293918847
match = 3523215443

[[format-3-2.instructions."fcvt.d.w".description]]
id = "inst-fcvt.d.w-behaviour"
normative = false
text = "`fcvt.d.w` converts a 32-bit signed integer, in integer register `xs1` into a double-precision\nfloating-point number in floating-point register `fd`.\nNote `fcvt.d.w` always produces an exact result and is unaffected by rounding mode.\n"

[format-3-2.instructions."fcvt.d.wu"]
mask = 4293918847
match = 3524264019

[[format-3-2.instructions."fcvt.d.wu".description]]
id = "inst-fcvt.d.wu-behaviour"
normative = false
text = "`fcvt.d.wu` converts a 32-bit unsigned integer in integer register `fs1` into a double-precision\nfloating-point number in floating-point register `fd`.\nNote `fcvt.d.wu` always produces an exact result and is unaffected by rounding mode.\n"

[format-3-3]
type = "type-3-3"

[format-3-3.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_float%, %rm%"

[format-3-3.instructions."fcvt.d.s"]
mask = 4293918847
match = 1107296339

[[format-3-3.instructions."fcvt.d.s".description]]
id = "inst-fcvt.d.s-behaviour"
normative = false
text = "The single-precision to double-precision conversion instruction, `fcvt.d.s` is encoded in the OP-FP\nmajor opcode space and both the source and destination are floating-point registers. The `xs2` field\nencodes the datatype of the source, and the `fmt` field encodes the datatype of the destination.\n`fcvt.d.s` will never round.\n"

[format-3-3.instructions."fcvt.s.d"]
mask = 4293918847
match = 1074790483

[[format-3-3.instructions."fcvt.s.d".description]]
id = "inst-fcvt.s.d-behaviour"
normative = false
text = "`fcvt.s.d` converts a double-precision floating-point number to a single-precision floating-point number.\n This is encoded in the OP-FP major opcode space and both the source and destination are floating-point\n registers. The `rs2` field encodes the datatype of the source, and the `fmt` field encodes the datatype\n of the destination. `fcvt.s.d` rounds according to the RM field\n"

[format-3-3.instructions."fsqrt.d"]
mask = 4293918847
match = 1509949523
description = "No description available.\n"

[format-4-3]
type = "type-4-3"

[format-4-3.repr]
default = "$name$ %rd_Register_int%, %rs1_Register_float%, %rs2_Register_float%"

[format-4-3.instructions."feq.d"]
mask = 4261441663
match = 2717917267
description = "No description available.\n"

[format-4-3.instructions."fle.d"]
mask = 4261441663
match = 2717909075
description = "No description available.\n"

[format-4-3.instructions."flt.d"]
mask = 4261441663
match = 2717913171
description = "No description available.\n"

[format-4-7]
type = "type-4-7"

[format-4-7.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_float%, %rs2_Register_float%"

[format-4-7.instructions."fmax.d"]
mask = 4261441663
match = 704647251
description = "No description available.\n"

[format-4-7.instructions."fmin.d"]
mask = 4261441663
match = 704643155
description = "No description available.\n"

[format-4-7.instructions."fsgnj.d"]
mask = 4261441663
match = 570425427
description = "No description available.\n"

[format-4-7.instructions."fsgnjn.d"]
mask = 4261441663
match = 570429523
description = "No description available.\n"

[format-4-7.instructions."fsgnjx.d"]
mask = 4261441663
match = 570433619
description = "No description available.\n"

[format-5-0]
type = "type-5-0"

[format-5-0.repr]
default = "$name$ %rd_Register_float%, %imm%(%rs1_Register_int%)"

[format-5-0.instructions.fld]
mask = 28799
match = 12295
description = "No description available.\n"

[format-6-15]
type = "type-6-15"

[format-6-15.repr]
default = "$name$ %rd_Register_float%, %rs1_Register_float%, %rs2_Register_float%, %rs3_Register_float%, %rm%"

[format-6-15.instructions."fmadd.d"]
mask = 100663423
match = 33554499
description = "No description available.\n"

[format-6-15.instructions."fmsub.d"]
mask = 100663423
match = 33554503
description = "No description available.\n"

[format-6-15.instructions."fnmadd.d"]
mask = 100663423
match = 33554511
description = "No description available.\n"

[format-6-15.instructions."fnmsub.d"]
mask = 100663423
match = 33554507
description = "No description available.\n"

[format-7-0]
type = "type-7-0"

[format-7-0.repr]
default = "$name$ %rs2_Register_float%, %imm%(%rs1_Register_int%)"

[format-7-0.instructions.fsd]
mask = 28799
match = 12327
description = "No description available.\n"

[mappings]
names = [
    "Register_int",
    "Register_float",
    "Mapping_round",
]
number = 32
Register_int = [
    "zero",
    "ra",
    "sp",
    "gp",
    "tp",
    "t0",
    "t1",
    "t2",
    "s0",
    "s1",
    "a0",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "s10",
    "s11",
    "t3",
    "t4",
    "t5",
    "t6",
]
Register_float = [
    "ft0",
    "ft1",
    "ft2",
    "ft3",
    "ft4",
    "ft5",
    "ft6",
    "ft7",
    "fs0",
    "fs1",
    "fa0",
    "fa1",
    "fa2",
    "fa3",
    "fa4",
    "fa5",
    "fa6",
    "fa7",
    "fs2",
    "fs3",
    "fs4",
    "fs5",
    "fs6",
    "fs7",
    "fs8",
    "fs9",
    "fs10",
    "fs11",
    "ft8",
    "ft9",
    "ft10",
    "ft11",
]
Mapping_round = [
    "rne",
    "rtz",
    "rdn",
    "rup",
    "rmm",
    "unknown",
    "unknown",
    "dyn",
]
