set = "RVZvkned"
width = 32

[formats]
names = [
    "format_1-0",
    "format_2-0",
]
parts = [
    [
        "vs2",
        5,
        "Register_vec",
    ],
    [
        "vd",
        5,
        "Register_vec",
    ],
    [
        "none",
        32,
        "u32",
    ],
    [
        "imm",
        32,
        "VInt",
    ],
    [
        "himm",
        32,
        "VInt",
        "hex",
    ],
]

[types]
names = [
    "type_1-0",
    "type_2-0",
]
type_1-0 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "none", top = 19, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_2-0 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "himm", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]

[format_1-0]
type = "type_1-0"

[format_1-0.repr]
default = "$name$ %vd%, %vs2%"

[format_1-0.instructions."vaesdf.vs"]
mask = 4262457471
match = 2785058935
description = "No description available.\n"

[format_1-0.instructions."vaesdf.vv"]
mask = 4262457471
match = 2717950071
description = "No description available.\n"

[format_1-0.instructions."vaesdm.vs"]
mask = 4262457471
match = 2785026167
description = "No description available.\n"

[format_1-0.instructions."vaesdm.vv"]
mask = 4262457471
match = 2717917303
description = "No description available.\n"

[format_1-0.instructions."vaesef.vs"]
mask = 4262457471
match = 2785124471
description = "No description available.\n"

[format_1-0.instructions."vaesef.vv"]
mask = 4262457471
match = 2718015607
description = "No description available.\n"

[format_1-0.instructions."vaesem.vs"]
mask = 4262457471
match = 2785091703
description = "No description available.\n"

[format_1-0.instructions."vaesem.vv"]
mask = 4262457471
match = 2717982839
description = "No description available.\n"

[format_1-0.instructions."vaesz.vs"]
mask = 4262457471
match = 2785255543
description = "No description available.\n"

[format_2-0]
type = "type_2-0"

[format_2-0.repr]
default = "$name$ %vd%, %vs2%, %himm%"

[format_2-0.instructions."vaeskf1.vi"]
mask = 4261441663
match = 2315264119
unsigned = true
description = "No description available.\n"

[format_2-0.instructions."vaeskf2.vi"]
mask = 4261441663
match = 2852135031
unsigned = true
description = "No description available.\n"

[mappings]
names = [
    "Register_vec",
]
number = 32
Register_vec = [
    "v0",
    "v1",
    "v2",
    "v3",
    "v4",
    "v5",
    "v6",
    "v7",
    "v8",
    "v9",
    "v10",
    "v11",
    "v12",
    "v13",
    "v14",
    "v15",
    "v16",
    "v17",
    "v18",
    "v19",
    "v20",
    "v21",
    "v22",
    "v23",
    "v24",
    "v25",
    "v26",
    "v27",
    "v28",
    "v29",
    "v30",
    "v31",
]
